-- INSERT INTO levels (tag,minimum,maximum) values ('A','0','100');
-- INSERT INTO levels (tag,minimum,maximum) values ('B','100','500');
-- INSERT INTO levels (tag,minimum,maximum) values ('C','500','1000');
-- INSERT INTO levels (tag,minimum,maximum) values ('D','1000','1500');